// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
package main

import (
	"fmt"
)

func main() {
	fmt.Println("A resource that creates Amazon Elastic Kubernetes Service (Amazon EKS) clusters.\n\nThis project has been deprecated, and is no longer supported. You are free to fork the code in the main branch and use it as a private resource type, but no support will be given by the AWS I&A or Cloudformation Teams.\n\n**USE AT YOUR OWN RISK**")
}
